const japanFacts = {
  culture: [
    "Japanese bowing has different angles depending on formality.",
    "The art of folding paper is called Origami, meaning 'folded paper'.",
    "Tatami floors are made from rice straw and regulate humidity.",
    "Wabi-sabi is a Japanese aesthetic that values imperfection.",
    "Shintoism and Buddhism are the two major religions in Japan.",
    "Kimonos are traditionally worn during ceremonies and festivals.",
    "Many Japanese homes have a genkan (entryway) to remove shoes.",
    "Seasonal festivals like Hanami celebrate nature’s beauty.",
    "Kabuki is a traditional theatre style with exaggerated makeup.",
    "The red torii gate marks the entrance to a sacred Shinto space.",
    "In Japanese, silence is often considered a sign of respect.",
    "The concept of 'Ma' means negative space or intentional emptiness.",
    "Ikebana is the disciplined art of flower arrangement.",
    "Japanese writing uses three scripts: Hiragana, Katakana, and Kanji.",
    "Samurai followed a code of honor called Bushidō.",
    "The Japanese tea ceremony emphasizes grace and mindfulness.",
    "Hanko (name seals) are still used in place of signatures.",
    "Japanese people celebrate both Christmas and Valentine's Day uniquely.",
    "Shōji screens are sliding paper doors found in traditional homes.",
    "Matsuri festivals often feature dancing, drumming, and portable shrines.",
    "School uniforms are worn by nearly all junior and high schoolers.",
    "Furin are wind chimes hung in summer to create a cooling sound.",
    "Gifting and wrapping gifts beautifully is a cultural norm.",
    "There are etiquette rules even for chopstick placement.",
    "The concept of 'gaman' means enduring with patience and dignity.",
    "Japanese shrines often have guardian lion-dogs called Komainu.",
    "Omamori are amulets sold at temples and shrines for protection.",
    "Cosplay and anime culture are deeply rooted in youth identity.",
    "Bonsai is the practice of growing miniature trees in containers.",
    "Tanabata festival celebrates the meeting of two star lovers in July.",
  ],
  food: [
    "Sushi began as a method of preserving fish in fermented rice.",
    "Ramen was imported from China but became a national favorite.",
    "Miso soup is a staple at Japanese breakfasts.",
    "Green tea is served with nearly every meal in Japan.",
    "Kaiseki is a traditional multi-course haute cuisine meal.",
    "Bento boxes are compartmentalized lunches with balanced portions.",
    "Takoyaki are octopus-filled balls of dough popular at festivals.",
    "Okonomiyaki is a savory pancake made with cabbage and toppings.",
    "Soba noodles are made from buckwheat and can be eaten cold.",
    "Tsukemono are pickled vegetables served as side dishes.",
    "Natto, fermented soybeans, has a strong flavor and sticky texture.",
    "Japanese curry is sweet, thick, and often served with rice and pork cutlet.",
    "Mochi is chewy rice cake often eaten during New Year celebrations.",
    "Tempura was introduced by the Portuguese and perfected by the Japanese.",
    "Unagi (eel) is a delicacy eaten especially in summer.",
    "Japanese street food includes delights like yakitori and taiyaki.",
    "Daifuku is a mochi stuffed with sweet fillings like red bean paste.",
    "Matcha desserts range from ice cream to cakes and lattes.",
    "Oden is a winter stew with eggs, daikon, and fish cakes.",
    "Sake is a fermented rice wine often served warm.",
    "Onigiri rice balls are a popular snack or lunch food.",
    "Japanese beef (like Kobe and Wagyu) is marbled and prized worldwide.",
    "Gyoza are pan-fried dumplings often eaten with vinegar and chili oil.",
    "Shabu-shabu is a hot pot dish where diners cook their food at the table.",
    "Tamagoyaki is a rolled sweet omelet served in sushi or bento.",
    "Chopstick etiquette forbids sticking them upright in rice (it mimics funeral rites).",
    "Fugu (pufferfish) can be deadly if not prepared by licensed chefs.",
    "Sakura-themed snacks appear every spring — even sakura Pepsi exists.",
    "Japan has unique Kit Kat flavors — from wasabi to purple yam.",
    "Umeboshi are pickled plums with an intensely sour-salty taste.",
  ],
  history: [
    "The Jōmon period marks the earliest known culture in Japan (14,000 BC).",
    "Samurai class ruled feudal Japan for over 600 years.",
    "The Meiji Restoration in 1868 ended shogunate rule and modernized Japan.",
    "Japan isolated itself from the world during the Edo period (1603–1868).",
    "The Great Kanto Earthquake of 1923 devastated Tokyo and Yokohama.",
    "Japan’s imperial family is the oldest continuing hereditary monarchy.",
    "The atomic bombings of Hiroshima and Nagasaki occurred in 1945.",
    "Japan surrendered in WWII on August 15, 1945, ending the war.",
    "Post-war Japan adopted a pacifist constitution under U.S. guidance.",
    "Anime and manga became global exports by the 1980s.",
    "The Heian period (794–1185) was a golden age of art and poetry.",
    "The kamikaze typhoons helped repel Mongol invasions in the 1200s.",
    "Zen Buddhism flourished under the Ashikaga shogunate.",
    "During the Sengoku era, warlords (daimyō) fought for power.",
    "Tokugawa Ieyasu unified Japan and started 250 years of peace.",
    "Commodore Perry opened Japan to the West in 1853.",
    "The first shogun, Minamoto no Yoritomo, rose to power in 1192.",
    "The Tale of Genji, written in the 11th century, is the world’s first novel.",
    "The samurai wore two swords: a katana and a wakizashi.",
    "Japan co-hosted the 2002 FIFA World Cup with South Korea.",
    "The bullet train (Shinkansen) began service in 1964.",
    "Oda Nobunaga, Toyotomi Hideyoshi, and Tokugawa Ieyasu are the Three Great Unifiers.",
    "Hirohito was emperor during World War II.",
    "The 2011 Tōhoku earthquake and tsunami caused the Fukushima disaster.",
    "In the late 1800s, Japan quickly industrialized and defeated Russia in war.",
    "Samurai lost official status during the Meiji era reforms.",
    "The flag of Japan symbolizes the sun — known as the ‘Land of the Rising Sun’.",
    "The Buddhist monk Kukai introduced kana writing to Japan.",
    "Osaka Castle played a major role in the unification of Japan.",
    "The Taika Reforms centralized power under the emperor in 645 AD.",
  ],
};

export default japanFacts;
